name: ns_json_serializable_example
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: 4.0.1

dev_dependencies:
  pedantic: ^1.11.0
  build_runner: 2.0.4
  json_serializable: 4.1.3
