name: old_json_serializable_example
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  json_annotation: 3.1.1

dev_dependencies:
  pedantic: ^1.11.0
  build_runner: 1.11.1
  json_serializable: 3.5.1
